---
- name: Download the kube-capacity archive.
  get_url:
    url: "{{ kube_capacity_download_url }}"
    dest: /tmp
    checksum: sha256:{{ kube_capacity_checksum_url }}
    mode: 0755
  register: kube_capacity_download

- name: Unarchive the kube-capacity archive.
  unarchive:
    src: "{{ kube_capacity_download.dest }}"
    dest: /tmp
    mode: 0755
    remote_src: true
  register: abc

- name: Copy the kube-capacity binary into place.
  copy:
    src: /tmp/kube-capacity
    dest: "{{ kube_capacity_bin_path }}"
    mode: 0755
    remote_src: true
  become: true
